### PR TITLE
Win64 msvc2019 64

### PR DESCRIPTION
**Pull request by cagnulein**

### CODE REVIEW

**Comment by cagnulein** [comment]
current state: it builds but it crashes on startup

**Comment by cagnulein** [comment]
image

**Comment by cagnulein** [comment]
[debug-mer__aoÃ»t_23_09_56_07_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12417966/debug-mer__aoA.t_23_09_56_07_2023.log)

**Comment by cagnulein** [comment]
[debug-mer__aoÃ»t_23_12_16_15_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12418107/debug-mer__aoA.t_23_12_16_15_2023.log)

**Comment by victorypoint** [comment]
@cagnulein, sure I can test whatever you need. Is there specific features to test and just the Windows build?

**Comment by cagnulein** [comment]
let's wait some more days, i have to fix a thing on the bluetooth side.
thanks again!

Il giorno gio 24 ago 2023 alle 19:02 Al Udell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
[debug-mer__aoÃ»t_23_17_26_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12462623/debug-mer__aoA.t_23_17_26_37_2023.log)

**Comment by cagnulein** [comment]
[Uploading debug-mar__aoÃ»t_29_15_57_31_2023.log…]()

**Comment by cagnulein** [comment]
[debug-mar__aoÃ»t_29_15_57_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12472898/debug-mar__aoA.t_29_15_57_31_2023.log)

**Comment by cagnulein** [comment]
[debug-mer__aoÃ»t_30_11_45_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12475257/debug-mer__aoA.t_30_11_45_40_2023.log)

**Pull request merged**
