### PR TITLE
android api 31

### PR DESCRIPTION
**Pull request by cagnulein**

### CODE REVIEW

**Comment by cagnulein** [comment]
https://developer.android.com/google/play/requirements/target-sdk

**Comment by cagnulein** [comment]
@marklogan17 _**[Bluetooth](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions): You must replace declarations for the [BLUETOOTH](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH) and [BLUETOOTH_ADMIN](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_ADMIN) permissions with [BLUETOOTH_SCAN](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_SCAN), [BLUETOOTH_ADVERTISE](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_ADVERTISE), or [BLUETOOTH_CONNECT](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_CONNECT) permissions. You no longer need to make LOCATION runtime permission requests for Bluetooth operations.**_

Finally!! :D

**Comment by marklogan17** [comment]
> @marklogan17 [Bluetooth](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions): You must replace declarations for the [BLUETOOTH](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH) and [BLUETOOTH_ADMIN](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_ADMIN) permissions with [BLUETOOTH_SCAN](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_SCAN), [BLUETOOTH_ADVERTISE](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_ADVERTISE), or [BLUETOOTH_CONNECT](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_CONNECT) permissions. _**You no longer need to make LOCATION runtime permission requests for Bluetooth operations.**_
> 
> Finally!! :D

So we never have to answer that question again?  Miracle!

**Comment by cagnulein** [comment]
@marklogan17 yes as soon as all the android devices will be on android 13 so.... NEVER :D

**Comment by marklogan17** [comment]
> @marklogan17 yes as soon as all the android devices will be on android 13 so.... NEVER :D

LOL.  So by 2025 we'll be good...

**Pull request merged**
