### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by grantland**
* Ignores build and user files
* Cleans up existing build dir

### CODE REVIEW

**Comment by cagnulein** [comment]
The majority of the files that you excluded are NEEDED for the iOS build! I can't merge this ;)

**Comment by grantland** [comment]
Ah, I thought the iOS files were autogenerated like the Android ones. I'll work to remedy this to just ignore non-iOS build dirs.

**Comment by cagnulein** [comment]
No unfortunately, not for the Apple Watch side :( thanks

**Comment by grantland** [comment]
Updated to retain iOS build dir

**Pull request merged**
