### PR TITLE
Removing FTMS only limitation for windows?

### PR DESCRIPTION
**Pull request by cagnulein**

### CODE REVIEW

**Comment by Middy2000** [comment]
[debug-Sun_Jul_14_07_48_43_2024 - not working.zip](https://github.com/user-attachments/files/16215886/debug-Sun_Jul_14_07_48_43_2024.-.not.working.zip)

Hi R.  

Two logs.  The log marked not working is using the new version of QZ that allowed cadence to show but is not allowing auto incline.

I tried to swap to the old version but QZ did not pick up any data until I did a reboot of the PC.  

After I rebooted I used the old version of QZ and auto incline is working.  I have attached this log.

Both logs do the same activity on the same course.

**Comment by cagnulein** [comment]
hi @Middy2000 log checked, thanks. but I don't see in the newer one the new logs that I added yesterday. Did you get this https://github.com/cagnulein/qdomyos-zwift/actions/runs/9922610727/artifacts/1698381962 from here https://github.com/cagnulein/qdomyos-zwift/actions/runs/9922610727 ?

**Comment by Middy2000** [comment]
Sorry, I didn't realise you had given me a new version to try.  I opened the message on my phone and it didn't show this.  Just downloading it now.

**Comment by Middy2000** [comment]
[debug-Sun_Jul_14_08_49_25_2024.log](https://github.com/user-attachments/files/16216010/debug-Sun_Jul_14_08_49_25_2024.log)

Same issue, no incline

**Comment by cagnulein** [comment]
perfect, this was expected, now i can see the new logs. I will update later today, I'm going out for lunch
Have a nice Sunday

**Comment by cagnulein** [comment]
good/bad news: I can see the same issue also on my pc with this build. I have to check whenever I changed something by mistake (i still think I didn't but anyway..)
I will keep you updated

**Comment by Middy2000** [comment]
I'm saying it's good news as it means it's nothing wrong with my equipment or anything that I'm doing.

I guess you've made a change some time ago that has affected this and it's not due to the one line of code you've added for my particular treadmill. 

But I guess you can't remember what you've changed.

Good luck finding it.

I'm not in a rush as I can use the version with no cadence.  I don't really pay much attention to cadence.

**Comment by cagnulein** [comment]
i got the issue (i'm testing now). It's because I didn't merge https://github.com/cagnulein/qdomyos-zwift/pull/1934
I will update you with the solution

**Comment by cagnulein** [comment]
@Middy2000 4 hours of working but i got it https://github.com/cagnulein/qdomyos-zwift/actions/runs/9929906806/artifacts/1699661136
let me know
FORZA INGHILTERRA :P

**Comment by Middy2000** [comment]
[debug-Mon_Jul_15_08_02_59_2024.zip](https://github.com/user-attachments/files/16234295/debug-Mon_Jul_15_08_02_59_2024.zip)

Hi R,

Two logs for you.  The small one is the first time I tried and for some reason QZ was not seeing any data and did not appear as a device in Zwift.  
I rebooted and then everything seemed OK.  The log from that session is enclosed.

**Comment by cagnulein** [comment]
in the first log seems something on the bluetooth dongle. It saws the treadmill, it connects to it but then it just disconnects automatically. Mysteries of windows

**Comment by Middy2000** [comment]
Yes I 100% think it was an issue with my setup rather than QZ.  I will keep reporting progress here over the next week or so but once it was working it was perfect.  Sorry for the extra work created but at least you have a master build now.

**Comment by Middy2000** [comment]
[debug-Mon_Jul_22_10_34_01_2024.zip](https://github.com/user-attachments/files/16331984/debug-Mon_Jul_22_10_34_01_2024.zip)

This is QZ working absolutely perfectly.

**Pull request closed without merging**
