### PR TITLE
Update python scripts to use AI.Server for OCR

### PR DESCRIPTION
**Pull request by victorypoint**

### CODE REVIEW

**Comment by victorypoint** [comment]
@cagnulein, here is my proposal for this update:

- New python code to use Codeproject.AI Server for OCR of Zwift onscreen incline, climb portal incline, and workout speed and incline. See - https://www.codeproject.com/AI/docs/
- New python code to support Zwift windowed mode. Can now be used with or without "Borderless Gaming" app to make Zwift fullscreen and borderless.
- Python install not needed on Windows QZ as AI Server includes it
- Zwift OCR capability is now available on all QZ supported platforms including mobile.
- To use Zwift OCR, QZ user needs access to a supported and dedicated PC, Mac, Docker, etc machine running AI Server on the same network. Note that AI Server can also be accessed via a publicly accessible server via external IP address.
- AI Server can be installed on the same Windows PC as QZ and Zwift, or a mix - for example-  AI.Server on a Windows PC or other supported platform, QZ on an iPhone/iPad/Android phone/tablet or other supported platform, Zwift on Windows PC or other supported platform.
- AI Server server needs a dedicated IP on local or public network if not accessible locally via localhost.
- AI Server OCR capability is fastest in "GPU mode" on a supported platform with supported CUDA-enabled nVidia graphics card. Otherwise, performance is still very responsive in "CPU mode".

For my testing setup, I have AI Server running on a Windows 11 PC with CUDA-enabled nVidia RTX 3060 GPU, with Zwift and QZ running on the same PC. I also have 2 Windows 10 laptops running Zwift and QZ, accessing the CUDA-enabled PC on same local network via IP address for OCR.

**Comment by cagnulein** [comment]
wow that's amazing @victorypoint ! thanks so much! I'm wondering 2 things:
1) maybe it would be better to leave the files as they are, and adding other 3 files? i'm saying so because maybe someone don't want to install a separate server. What do you think?
2) on mobile, since i don't have python, i can simply send the screenshot via socket in c++ without using python, right?

**Comment by victorypoint** [comment]
> i don't get this. Why we should change the python version? if you want, we can create 2 pkg for windows: one with AI.Server and one with the actual python. The python we could include with QZ would be based on the same install package and components they use.

Python 3.7 is what the folks at Codeproject use for their AI Server product. They find it's more stable, lightweight, and a bit faster than new Python for PaddleOCR performance in  both GPU and CPU modes.

Two Windows install packages could work fine. What do you want to do with Windows msvc builds? I haven't tested the new python code on that build yet.

**Comment by cagnulein** [comment]
> Python 3.7 is what the folks at Codeproject use for their AI Server product. They find it's more stable, lightweight, and a bit faster than new Python for PaddleOCR performance in both GPU and CPU modes.

ok so I will keep the current python version for the actul paddleocr version package.
Since Codeproject is installing it by their install package, I don't need to put the 3.7 in the  CI.



> Two Windows install packages could work fine. What do you want to do with Windows msvc builds? I haven't tested the new python code on that build yet.

the msvc are useful for the bluetooth side of windows: bluetooth it's a nightmare with the classic mingw build.

**Comment by victorypoint** [comment]
> ok so I will keep the current python version for the actul paddleocr version package. Since Codeproject is installing it by their install package, I don't need to put the 3.7 in the CI.

Good! Let's keep the current Python at 3.10.11. If you want a bit more OCR speed and reduce download size, we can change it to Python 3.7.

I'm looking over the packages in Python 3.10.11 and noticed that we have both Paddlepaddle CPU and GPU versions installed. We only need Paddlepaddle CPU so GPU version can be deleted. This will make the download a bit smaller:
```
paddlepaddle          2.4.2
paddlepaddle-gpu      2.4.2.post117
```

To delete paddlepaddle-gpu:
`python -m pip uninstall paddlepaddle-gpu`

**Comment by victorypoint** [comment]
> done, let's see if it builds correctly

Here are the Python 3.7 components and updates to install:

- python -m pip install --upgrade pip
- python -m pip install --upgrade setuptools
- python -m pip install "protobuf<=3.20.2,>=3.1.0"
- python -m pip install paddlepaddle==2.5.1
- python -m pip install paddleocr
- python -m pip install imutils
- python -m pip install "Pillow<10.0.0"
- python -m pip install opencv-python  
- python -m pip install numpy
- python -m pip install pywin32

**Comment by victorypoint** [comment]
> @victorypoint i merged this with the master and #1860 . is this still right? (check my last commit here)

Yes. Looks good.

**Comment by cagnulein** [comment]
got it! i will add these in new CI build, thanks!

Il giorno lun 11 dic 2023 alle 19:00 Al Udell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok done, let's see if it builds!

**Comment by cagnulein** [comment]
built! @victorypoint give it a try if you can. I also was wondering: could be the case to include also the AI server on this build? so QZ can start the installer the first time for example. What do you think? Otherwise people will download it, but they don't know about the requirements.

**Comment by victorypoint** [comment]
> built! @victorypoint give it a try if you can. I also was wondering: could be the case to include also the AI server on this build? so QZ can start the installer the first time for example. What do you think? Otherwise people will download it, but they don't know about the requirements.

Ok thanks! I will test right away. I was communicating with the AI Server people about the same thing recently. They currently don't have an API for custom install but are developing one soon. Another complication is in order to use GPU-powered OCR, the user must have a supported nVidia card, and must have nVidia CUDA and cuDNN software installed as well. I think the best we can do for now is document the installation steps for AI Server with it's OCR module, and optionally install Borderless Gaming. We could also include a check in QZ to popup a message stating if AI Server cannot be found and needs to be installed.

**Comment by victorypoint** [comment]
@cagnulein, I just finished testing the latest builds. Sorry for the delay. I made sure to remove all python entries in my Windows PATH to no conflict and ensured CUDA and Ai.Server components installed.

windows-msvc2019-ai-server-binary-no-python.zip - I noticed the auto OCR .py scripts are not included in this build. Did we want to include them and use the python that's included with AI.Server?

windows-msvc2019-ai-server-binary.zip - the QZ python and .py scripts performed rock-solid. All 3 auto OCR features worked great in PaddleOCR GPU mode. Nice work!

**Comment by cagnulein** [comment]
great news @victorypoint 



> windows-msvc2019-ai-server-binary-no-python.zip - I noticed the auto OCR .py scripts are not included in this build. Did we want to include them and use the python that's included with AI.Server?

i'm using the same python names, overwriting them if you are using the ai server build. because i thought that someone is using the ai server build don't want to use the classic paddle one. What do you think? This was the easiest way to implement it ;)

**Comment by victorypoint** [comment]
> great news @victorypoint
> 
> > windows-msvc2019-ai-server-binary-no-python.zip - I noticed the auto OCR .py scripts are not included in this build. Did we want to include them and use the python that's included with AI.Server?
> 
> i'm using the same python names, overwriting them if you are using the ai server build. because i thought that someone is using the ai server build don't want to use the classic paddle one. What do you think? This was the easiest way to implement it ;)

AI.Server will install the classic CPU PaddleOCR if an nVidia graphics card is not found so it will work both ways. So if you include the same OCR .py scripts and have QZ use the AI.Server python at 'C:\Program Files\CodeProject\AI\modules\OCR\bin\windows\python37\venv\Scripts\python.exe', it should all work fine.

**Comment by cagnulein** [comment]
perfect, it's building with this modification! thanks for the clarification!

**Comment by victorypoint** [comment]
> build ready when you have time @victorypoint https://github.com/cagnulein/qdomyos-zwift/actions/runs/7240147087

Thanks @cagnulein. I tested the latest 'windows-msvc2019-ai-server-binary-no-python.zip' build.

First, I confirmed that from the command-line, zwift-incline.py works with treadmill on and Zwift workout running:
```
cd "C:\Program Files\CodeProject\AI\modules\OCR\bin\windows\python37\venv\Scripts"
python.exe C:\Temp\qdomyos-zwift\zwift-incline.py - incline is returned
```

Next, I tested QZ but ran into some problems. QZ is communicating the treadmill speed to Zwift (dircon), however no tiles are showing in QZ. The QZ log is showing this error so I suspect it's not finding the AI.Server python. Can you confirm the correct path to python is used (as noted previously)?

```
Line  742: Mon Dec 18 12:22:46 2023 1702916566601 Debug: .\bluetooth.cpp void __cdecl bluetooth::debug(const class QString &) "python << ERR Traceback (most recent call last):\r\n  File \"zwift-incline.py\", line 9, in <module>\r\n    import cv2\r\nModuleNotFoundError: No module named 'cv2'\r\n"
Line  743: Mon Dec 18 12:22:46 2023 1702916566701 Debug: .\windows_zwift_incline_paddleocr_thread.cpp class QString __cdecl windows_zwift_incline_paddleocr_thread::runPython(class QString) run >>  "zwift-incline.py"
```

**Comment by cagnulein** [comment]
@victorypoint ah! no, actually qz uses the local path of python https://github.com/cagnulein/qdomyos-zwift/blob/21f977ad44470cbbd40dfa2e5293f205f98c839b/src/windows_zwift_workout_paddleocr_thread.cpp#L54

how could the qz app know where the AI. server python is installed? what do you suggest?

**Comment by victorypoint** [comment]
> @victorypoint ah! no, actually qz uses the local path of python
> 
> https://github.com/cagnulein/qdomyos-zwift/blob/21f977ad44470cbbd40dfa2e5293f205f98c839b/src/windows_zwift_workout_paddleocr_thread.cpp#L54
> 
> how could the qz app know where the AI. server python is installed? what do you suggest?

@cagnulein, can you obtain the root drive where QZ is located and go relative from there? This also works if you hardcode the entire path:

"C:\Program Files\CodeProject\AI\modules\OCR\bin\windows\python37\venv\Scripts\python.exe" zwift-incline.py

**Comment by cagnulein** [comment]
yeah but if the user set the default one: what if the users change the
ai.server path? :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 dic 2023 alle 19:48 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein, when we write up documentation for using AI.Server, we can just say to make sure to install it to default location in C:\Program Files\CodeProject\AI\. I think that's the best we can do.

**Comment by cagnulein** [comment]
Ok it makes sense :) i'm doing it right now :P

**Comment by cagnulein** [comment]
@victorypoint i don't why but I can make a modification in the files because it says that it's locked from you.
can you commit these changes in your fork?

change in src/windows_zwift_workout_paddleocr_thread.cpp and in src/windows_zwift_incline_paddleocr_thread.cpp

the line

QString updatedPath = currentPath + ";" + QCoreApplication::applicationDirPath() + "\\python\\x64";

with

QString updatedPath = currentPath + ";" + QCoreApplication::applicationDirPath() + "\\python\\x64;C:\\Program Files\\CodeProject\\AI\\modules\\OCR\\bin\\windows\\python37\\venv\\Scripts";

thanks

**Comment by victorypoint** [comment]
> @victorypoint i don't why but I can make a modification in the files because it says that it's locked from you. can you commit these changes in your fork?
> 
> change in src/windows_zwift_workout_paddleocr_thread.cpp and in src/windows_zwift_incline_paddleocr_thread.cpp
> 
> the line
> 
> QString updatedPath = currentPath + ";" + QCoreApplication::applicationDirPath() + "\python\x64";
> 
> with
> 
> QString updatedPath = currentPath + ";" + QCoreApplication::applicationDirPath() + "\python\x64;C:\Program Files\CodeProject\AI\modules\OCR\bin\windows\python37\venv\Scripts";
> 
> thanks

@cagnulein, okay done. Sorry I don't know why those files were locked. Perhaps I should delete the fork on my side?

**Comment by victorypoint** [comment]
@cagnulein, I just tested the new windows-msvc2019-ai-server-binary-no-python.zip build and same problem unfortunately. I'm thinking maybe the space is stripped from "program files"?

**Comment by cagnulein** [comment]
argh @victorypoint that's a github issue because it's stripped the `\\`

the right modification is

`QString updatedPath = currentPath + ";" + QCoreApplication::applicationDirPath() + "\\python\\x64";`

to

`QString updatedPath = currentPath + ";" + QCoreApplication::applicationDirPath() + "\\python\\x64;C:\\Program Files\\CodeProject\\AI\\modules\\OCR\\bin\\windows\\python37\\venv\\Scripts";`

if it still doesn't work, you could be right, it could be an issue in the space of the Program Files folder. Let's try first in this way.

Thanks for your time

**Comment by victorypoint** [comment]
> argh @victorypoint that's a github issue because it's stripped the `\\`
> 
> the right modification is
> 
> `QString updatedPath = currentPath + ";" + QCoreApplication::applicationDirPath() + "\\python\\x64";`
> 
> to
> 
> `QString updatedPath = currentPath + ";" + QCoreApplication::applicationDirPath() + "\\python\\x64;C:\\Program Files\\CodeProject\\AI\\modules\\OCR\\bin\\windows\\python37\\venv\\Scripts";`
> 
> if it still doesn't work, you could be right, it could be an issue in the space of the Program Files folder. Let's try first in this way.
> 
> Thanks for your time

Yes, I caught that and made the correct modification with the double \\. Still no luck with the testing unfortunately.

**Comment by victorypoint** [comment]
@cagnulein, could this line be causing the problem?

`process.start("python\\x64\\python.exe", QStringList(command.split(' ')));`

**Comment by cagnulein** [comment]
> `process.start("python\\x64\\python.exe", QStringList(command.split(' ')));`

ah you're right!

let's try

`process.start("python.exe", QStringList(command.split(' ')));`

instead!

**Comment by skoregon** [comment]
Is it possible with the ocr offload this part of project could be implemented in the raspberry pi branch using a camera on the pi to capture the incline display on the screen and send it to ai server?

**Comment by cagnulein** [comment]
@skoregon i don't see any downside about your idea apart the power of the raspberry: but i guess using the raspberry as a input video and streaming it to the ai server it could be reasonable for a raspberry 4 or even a 3. you can definitely try!

**Comment by cagnulein** [comment]
let me know if I can help you somehow @victorypoint

**Comment by cagnulein** [comment]
ok we can set a #define in the secret file in the CI so that one build in the standard way, and with the define defined it will build in another.

could you please write me here the portion of the code that work on the AI.server build? so i can add them on the cpp file under ifdef



> Also, the windows-msvc2019-ai-server-binary-no-python.zip build contains the python folder which tripped me up a bit during testing. Anyways, let me know what you think.

i'm checking it

**Comment by cagnulein** [comment]
> Also, the windows-msvc2019-ai-server-binary-no-python.zip build contains the python folder which tripped me up a bit during testing. Anyways, let me know what you think.

fixed.

i discovered that i can't push file locally, but I can edit files directly on github. That's strange!

**Comment by victorypoint** [comment]
@cagnulein, this should work:

process.start("C:\\Program Files\\CodeProject\\AI\\modules\\OCR\\bin\\windows\\python37\\venv\\Scripts\\python.exe", QStringList(command.split(' ')));

**Comment by victorypoint** [comment]
> @cagnulein, this should work:
> 
> process.start("C:\Program Files\CodeProject\AI\modules\OCR\bin\windows\python37\venv\Scripts\python.exe", QStringList(command.split(' ')));

Sorry, it stripped the double \\

**Comment by cagnulein** [comment]
if I did everything right, this is the right build https://github.com/cagnulein/qdomyos-zwift/actions/runs/7290523050

**Comment by cagnulein** [comment]
this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7290732413 actually
I used a new aiserver.h file for this

**Comment by victorypoint** [comment]
> this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7290732413 actually I used a new aiserver.h file for this

Ok, thanks @cagnulein. Will get this tested tonight.

**Comment by victorypoint** [comment]
@cagnulein, the windows-msvc2019-ai-server-binary-no-python.zip build is working beautifully with AI.Server python now. Thank-you! I confirmed that the zip no longer contains python folder however I noticed that the windows-msvc2019-ai-server-binary.zip build doesn't contain python either (it should). I haven't checked all the other builds for python folder.

**Comment by cagnulein** [comment]
> @cagnulein, the windows-msvc2019-ai-server-binary-no-python.zip build is working beautifully with AI.Server python now. Thank-you! I confirmed that the zip no longer contains python folder however I noticed that the windows-msvc2019-ai-server-binary.zip build doesn't contain python either (it should). I haven't checked all the other builds for python folder.

that's a great news @victorypoint ! why the ai server binary should contains the python folder? yesterday i removed it on purpose thinking that the ai server python version would be enough. am i wrong?

**Comment by victorypoint** [comment]
> > @cagnulein, the windows-msvc2019-ai-server-binary-no-python.zip build is working beautifully with AI.Server python now. Thank-you! I confirmed that the zip no longer contains python folder however I noticed that the windows-msvc2019-ai-server-binary.zip build doesn't contain python either (it should). I haven't checked all the other builds for python folder.
> 
> that's a great news @victorypoint ! why the ai server binary should contains the python folder? yesterday i removed it on purpose thinking that the ai server python version would be enough. am i wrong?

Ah! Okay you got me madly searching in our previous conversations about this because I forget 😂. So I think we discussed having 2 versions of QZ AI.Server builds - one with built-in python and one without. It's totally up to you if you want to eliminate the built-in one. Not sure why we decided that?

**Comment by cagnulein** [comment]
hahaha we did so many versions that i don't remember either :) 

anyway if an user would like to  use the classic python build it has on the classic windows build so i guess we should be ready to go

i will check again the previous conversation just to be sure and then i will merge it. i have already an user that would like to try it :)

**Comment by cagnulein** [comment]
mmm i was checking the changes from the phone before merging but there is something that i probably did wrong. i changed by mistake the classic build too. before merging i will check from the mac in the next days

have a nice day @victorypoint thanks for you help and if we will not talk sooner, merry Christmas to you and to your family!

**Comment by victorypoint** [comment]
@cagnulein, yes Merry Christmas to you and your wonderful family as well 🥰. We are sticking close to home this holiday season so I'm available to test and help.

**Comment by cagnulein** [comment]
nevermind, I saw wrongly from the phone. All fine! I'm merging!

**Comment by victorypoint** [comment]
@cagnulein, just testing the latest nightly build of 'windows-msvc2019-ai-server-binary.zip' and I find that although AI.Server OCR works fine, this build is not sending ADB swipes to the TM for some strange reason. I also tested nightly build of 'windows-binary.zip' and confirmed that OCR and swipes are working fine. Here are my testing logs:

[aiserver-no-swipes2-debug-Mon_Jan_1_15_17_52_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13810738/aiserver-no-swipes2-debug-Mon_Jan_1_15_17_52_2024.log)

[aiserver-no-swipes-debug-Mon_Jan_1_11_42_38_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13810739/aiserver-no-swipes-debug-Mon_Jan_1_11_42_38_2024.log)

[working-debug-Mon_Jan_1_15_34_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13810737/working-debug-Mon_Jan_1_15_34_57_2024.log)

**Comment by victorypoint** [comment]
@cagnulein, I also just tested latest nightly build of 'windows-msvc2019-binary.zip' and it works fine with OCR and swipes. So the swipe problem just seems to be a problem specifically with 'windows-msvc2019-ai-server-binary.zip' build.

[msvc-working-debug-Tue_Jan_2_11_30_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13811478/msvc-working-debug-Tue_Jan_2_11_30_25_2024.log)

**Comment by cagnulein** [comment]
the problem is that the trainProgramSignals function is not called. I'm checking why, I guess it's something about compiler optimization

**Comment by cagnulein** [comment]
@victorypoint could you please try this build? https://github.com/cagnulein/qdomyos-zwift/actions/runs/7395469444

I tried to sync the events

Let me know!

**Comment by victorypoint** [comment]
@cagnulein, you nailed it. Thank-you! This Ai.Server + nVidia combo is absolutely the fastest and most responsive QZ auto-incline method I've tested. Even faster than the old bike hack method. Awesome work!

[debug-Wed_Jan_3_11_24_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13820867/debug-Wed_Jan_3_11_24_11_2024.log)

**Comment by cagnulein** [comment]
Great! I'm merging it!

**Pull request merged**
