### PR TITLE
Secondary branch for modbus treadmill with increased time and ?linux

### PR DESCRIPTION
**Pull request by jjbrough**
with increased time and ?linux

### CODE REVIEW

**Comment by jjbrough** [comment]
OK, I went back to when I first created this.
This is the conflict with the bluetooth.cpp that I think messed it up in the beginning.
Do you know the best way to resolve this conflict? I think I didn't do it right last time.

**Comment by cagnulein** [comment]
i did now for you

**Comment by jjbrough** [comment]
Awesome!

**Comment by jjbrough** [comment]
Looks like there's another conflict:
<<<<<<< secondary_branch
        settings.setValue(QStringLiteral("miles_unit"), miles);
        settings.setValue(QStringLiteral("bluetooth_no_reconnection"), bluetooth_no_reconnection);
        settings.setValue(QStringLiteral("bluetooth_relaxed"), bluetooth_relaxed);
        settings.setValue(QStringLiteral("bike_cadence_sensor"), bike_cadence_sensor);
        settings.setValue(QStringLiteral("bike_power_sensor"), bike_power_sensor);
        settings.setValue(QStringLiteral("battery_service"), battery_service);
        settings.setValue(QStringLiteral("service_changed"), service_changed);
        settings.setValue(QStringLiteral("bike_wheel_revs"), bike_wheel_revs);
        settings.setValue(QStringLiteral("run_cadence_sensor"), run_cadence_sensor);
        settings.setValue(QStringLiteral("nordictrack_10_treadmill"), nordictrack_10_treadmill);
        settings.setValue(QStringLiteral("reebok_fr30_treadmill"), reebok_fr30_treadmill);        
=======
        settings.setValue(QZSettings::miles_unit, miles);
        settings.setValue(QZSettings::bluetooth_no_reconnection, bluetooth_no_reconnection);
        settings.setValue(QZSettings::bluetooth_relaxed, bluetooth_relaxed);
        settings.setValue(QZSettings::bike_cadence_sensor, bike_cadence_sensor);
        settings.setValue(QZSettings::bike_power_sensor, bike_power_sensor);
        settings.setValue(QZSettings::battery_service, battery_service);
        settings.setValue(QZSettings::service_changed, service_changed);
        settings.setValue(QZSettings::bike_wheel_revs, bike_wheel_revs);
        settings.setValue(QZSettings::run_cadence_sensor, run_cadence_sensor);
        settings.setValue(QZSettings::nordictrack_10_treadmill, nordictrack_10_treadmill);
        settings.setValue(QZSettings::reebok_fr30_treadmill, reebok_fr30_treadmill);
        settings.setValue(QZSettings::zwift_click, zwift_click);
        settings.setValue(QZSettings::zwift_play, zwift_play);
        settings.setValue(QZSettings::zwift_play_emulator, zwift_play_emulator);
>>>>>>> master

**Comment by cagnulein** [comment]
fixed

**Pull request closed without merging**
