### PR TITLE
#2102 reorganisation of file system

### PR DESCRIPTION
**Pull request by drmason789**
#2102

### CODE REVIEW

**Comment by cagnulein** [comment]
Thanks a lot, I will check this tomorrow!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 7 feb 2024 alle 22:58 David Mason ***@***.***>
ha scritto:

**Comment by drmason789** [comment]
@cagnulein I updated the pbxproj file as requested. I'm not in a position to build this AFAIK. It might be necessary to add to the HEADER_SEARCH_PATHS a few items as I have done in the .pri file:

../src/devices
../src/virtualdevices

**Comment by cagnulein** [comment]
No problem, thanks!
I will do myself
Doing this manually on xcode was a nightmare

Il giorno mer 7 feb 2024 alle 23:00 David Mason ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i did it in the #2107 (just added the include dir in the xcode file and I can pull it in this branch since it's your and I wasn't able to modify it)
thanks!

**Pull request closed without merging**
