### PR TITLE
Gear UI on zwift #2391

### PR DESCRIPTION
**Pull request by cagnulein**

### CODE REVIEW

**Comment by cagnulein** [comment]
debug-Fri_Sep_6_11_07_13_2024.log.zip

**Comment by cagnulein** [comment]
debug-Fri_Sep_6_12_05_34_2024.log.zip

**Comment by svc1234** [comment]
I would like to use the zwift gears exactly as shown in your video, but without the zwift click controllers. I would like to use the app along with a bluetooth volume remote to change the gears.

Also tried to change the wahoo ID number to something besides 0 and it still comes up at Wahoo 0000 33. I have 4 trainers setup in a room and I have everyone riding sometimes and we can’t distinguish who’s on what.

**Comment by cagnulein** [comment]
Ok I will build it in the next days.
For the ID is working fine, it's just a zwift cache issue. You can try to
reinstall it (once zwift shows an ip with a name it saves it as it is)

Consider also to join patreon to support the app!
https://www.patreon.com/cagnulein

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 26 ott 2024 alle 17:49 svc1234 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Yes it should work.
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 26 ott 2024 alle 17:59 svc1234 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@svc1234 did it work? i finish the implementation, i will do some test in the next days. are you still interested on this?

**Comment by svc1234** [comment]
Let me know when I can download it and I will try.

**Comment by cagnulein** [comment]
Ok, I will let you know, probably this weekend

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 30 ott 2024 alle ore 11:52 svc1234 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@svc1234 are you on android or ios with qz?

**Comment by cagnulein** [comment]
This is the setting for this

**Comment by cagnulein** [comment]
and on zwift you have to pair exactly as this

image

**Comment by cagnulein** [comment]
tested on both android and ios

**Comment by svc1234** [comment]
I am on ios but would like to also try android to see which works best for
me.

**Comment by svc1234** [comment]
I do not have the zwift play controllers or the zwift click.

**Comment by svc1234** [comment]
Your screenshot shows that you paired the zwift play controllers. What do I
pair to the controls tab?

**Comment by cagnulein** [comment]
Hah sorry you don't need that part

**Comment by svc1234** [comment]
Ok thanks.

**Comment by svc1234** [comment]
I will try it on the weekend.

Thank you!

**Comment by cagnulein** [comment]
ok let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 31 ott 2024 alle 19:02 svc1234 ***@***.***> ha
scritto:

**Comment by svc1234** [comment]
I tried it. It works. Only thing is that Zwift doesn’t automatically load
up the calibration for the virtual gears so the gears are really off. Gear
1  is way too hard!

Also, do you have the iOS version ready?

**Comment by svc1234** [comment]
Also noticed that its using an infinite number of gears. It can go up to
gear numbers over 100?

**Comment by cagnulein** [comment]
@svc1234 I don't remember which trainer do you have? Yes I can also build the ios version 

Let me know

**Comment by svc1234** [comment]
I have the tacx neo 2t.

**Comment by cagnulein** [comment]
Yes for your trainer now gears are infinite because they are an offset applied to the resistance requested from zwift. I'm developing a new feature that control the gears directly from the tacx custom Bluetooth charaterstic if you are interested

**Comment by cagnulein** [comment]
You can use gear gain to 0.5 or less to have minor increments of the gears

**Comment by svc1234** [comment]
Yes, I would be interested!

**Comment by cagnulein** [comment]
@svc1234 done https://github.com/cagnulein/qdomyos-zwift/actions/runs/11665270557

it's very experimental, so let me know how it works. gear are now using the wahoo gear table that you can access via the bike settings, wahoo options.

**Comment by cagnulein** [comment]
new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/11665888221

**Pull request merged**
