### PR TITLE
Tidy up Ant and implement FE-C

### PR DESCRIPTION
**Pull request by stewpend0us**
Seems like a lot of duplication across the ant classes. figured I'd start by cleaning that up first? not sure if the new file will even be built yet because it's not referenced? but wanted to see what happens.

#1930

### CODE REVIEW

**Comment by cagnulein** [comment]
sure give it a try! when i started the ant+ implementation i felt like an elephant in a glass store :)

**Comment by cagnulein** [comment]
i approved the ci, its building now

**Comment by stewpend0us** [comment]
Send like it builds at least.... Any tips on how to test?

**Comment by cagnulein** [comment]
nope it fails, check this
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7382214735/job/20084524808


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 2 gen 2024 alle 12:46 Stewart ***@***.***> ha
scritto:

**Comment by stewpend0us** [comment]
Ohh I saw the other platforms building. Is the Ant stuff only included on Android?

**Comment by cagnulein** [comment]
> Ohh I saw the other platforms building. Is the Ant stuff only included on Android?

yes :)

**Comment by stewpend0us** [comment]
Think it might have just been the extra "}" can you re-run? Is the CI stuff free? I can see if I can get setup to build locally if it's a problem

**Comment by cagnulein** [comment]
> Think it might have just been the extra "}" can you re-run? Is the CI stuff free? I can see if I can get setup to build locally if it's a problem

now it should approved forever. yes CI for now is free, so no problem :) if you want you can setup it locally but it's for sure a pain in the ass :D I warned you :D

**Comment by stewpend0us** [comment]
Seems to still need approval?

**Comment by cagnulein** [comment]
yes i don't know why it needs always the approval, i will investigate this today, maybe i should approve you somehow

**Comment by stewpend0us** [comment]
I think I need to just get set up locally. Too embarrassing to be committing all my stupid mistakes!

**Comment by cagnulein** [comment]
hahah no problem at all! i'm doing the same when i'm doing modification on my phone :)

**Comment by stewpend0us** [comment]
okkkk. I think this one might go through finally. I noticed that the frequency settings are all just slightly different across the classes is there a reason for that?

**Comment by cagnulein** [comment]
i remember that each class has its own frequency in the ant+ data sheet

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle 05:56 Stewart ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i guess the next one will be the one :) !

**Comment by stewpend0us** [comment]
Lol. So painful to wait 20 minutes for a typo

**Comment by stewpend0us** [comment]
NOW. Any tips on how to test this?

**Comment by stewpend0us** [comment]
This seemed to work...at least as well as it did for me before. I got power (seemed right) and speed (at like 2-3x what I'd expect) same as before. Heart didn't go from watch to the app maybe my settings are wrong? obviously nothing new here just the "clean up"

**Comment by cagnulein** [comment]
> Heart didn't go from watch to the app maybe my settings are wrong?

ant heart setting is enabled in qz?

**Comment by stewpend0us** [comment]
Yes

**Comment by cagnulein** [comment]
i will try the build too to check if it's working on my side. i usually try with a polar hr ant+ device

**Comment by cagnulein** [comment]
I can confirm you that this APK and ANT Heart works on my side! So good job!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle ore 15:47 Stewart ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@stewpend0us Any news?

**Comment by stewpend0us** [comment]
No. :( sorry

**Comment by cagnulein** [comment]
Ok are you still want you to do it or just abandoned it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 feb 2024 alle 13:10 Stewart ***@***.***> ha
scritto:

**Pull request closed without merging**
