### PR TITLE
Test Videos with higher fps Rates

### PR DESCRIPTION
**Pull request by Bepo7012**

### CODE REVIEW

**Comment by Bepo7012** [comment]
Yes you can merge this. I can't imagine an impact to existing "normal" videos, the recalculation is only done if the difference between gpx and video is greater 60 seconds which should not happen except of videos that are fastened by default.

**Comment by Bepo7012** [comment]
And: It's working like a Charm :-) Played around with a few videos yesterday, each was nicely played. for one video i had to use 240 fps becuse it was originally already recorded with 60fps.

**Comment by cagnulein** [comment]
@Bepo7012 great! you're now our Steven Spielberg :D

**Comment by Bepo7012** [comment]
:-D

**Pull request merged**
