### PR TITLE
Bluetooth volume controls on Android not working to change gears (Issue #2614)

### PR DESCRIPTION
**Pull request by cagnulein**

### CODE REVIEW

**Comment by ogperalta** [comment]
Hola...tengo este mismo error en la versión 2.18.24...el teléfono que estoy usando es un huawei y9 prime pero también lo he probado en un motorola moto g84...

**Comment by cagnulein** [comment]
@ogperalta Share a debug log and I will check your setup https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by ogperalta** [comment]
[debug-Thu_May_29_17_47_37_2025.log](https://github.com/user-attachments/files/20512411/debug-Thu_May_29_17_47_37_2025.log)

**Comment by ogperalta** [comment]
@cagnulein en este otro archivo solo intenté subir los cambios con el botón de los audífonos bluetooth
[debug-Thu_May_29_20_05_36_2025.log](https://github.com/user-attachments/files/20513539/debug-Thu_May_29_20_05_36_2025.log)

**Comment by ogperalta** [comment]
@cagnulein Este log es donde usé solo los botones Bluetooth, por favor mirar este https://github.com/user-attachments/files/20513539/debug-Thu_May_29_20_05_36_2025.log

**Comment by cagnulein** [comment]
@ogperalta which android version do you have? Do you see the volume increase or degrees on your system when you're pressing it? I guess I will need a bug report from android directly in order to understand your issue

**Comment by ogperalta** [comment]
@cagnulein estoy usando un teléfono huawei y9 prime con emui 12.0.0 (Android 11)

**Comment by cagnulein** [comment]
Ok I need a bug report from android to understand which is the issue on
your side

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 giu 2025 alle 02:10 ogperalta ***@***.***> ha
scritto:

**Pull request merged**
