### PR TITLE
Fitshow support

### PR DESCRIPTION
**Pull request by p3g4asus**
This patch basically extends qdomyos-zwift Fitshow treadmills support. It deletes `fassitreadmill` and `jkfitnesstreadmill` classes because both are supported by the more complete `fitshowtreadmill` module. 
This PR implements also some changes that make the build under VS2019 possible (see changes in `main.cpp`, `virtualbike.cpp` and `homeform.cpp`). 
About the new `fitshowtreadmill` please note:
1) it is even more complete than necessary
2) It is designed to compile **and work** under windows 10 (please look at line 678 of the file `fitshowtreadmill.cpp`: it should copied in all other device classes to let them work under windows 10).
3) it requires a new setting (user ID) which I implemented in the `settings.qml`

### CODE REVIEW

**Comment by cagnulein** [comment]
you did an amazing job @p3g4asus !
i will merge this when i will pushed the 2.3.x version on the stores.
Thank you so much!

**Comment by cagnulein** [comment]
@p3g4asus also, as i promised, https://github.com/cagnulein/qdomyos-zwift/commit/075df393efca9cb508a048966dbbddeada88897b

**Comment by p3g4asus** [comment]
> 
> 
> you did an amazing job @p3g4asus !
> i will merge this when i will pushed the 2.3.x version on the stores.
> Thank you so much!

You are welcome: keep up your wonderful work!

**Comment by p3g4asus** [comment]
> 
> 
> @p3g4asus also, as i promised, [075df39](https://github.com/cagnulein/qdomyos-zwift/commit/075df393efca9cb508a048966dbbddeada88897b)

That sounds like a nasty bug fixed. Congrats!

**Comment by cagnulein** [comment]
> (please look at line 678 of the file fitshowtreadmill.cpp: it should copied in all other device classes to let them work under windows 10).

@p3g4asus are you not using Mingw on windows, isn't it? because with Mingw i don't have this issue.

**Comment by p3g4asus** [comment]
> @p3g4asus are you not using Mingw on windows, isn't it? because with Mingw i don't have this issue.

I am using msvc2019. I assume this is the problem.

**Comment by cagnulein** [comment]
Yep i guess so. Maybe we should use a different ifdef condition

Il dom 28 feb 2021, 14:55 p3g4asus <notifications@github.com> ha scritto:

**Pull request merged**
