### PR TITLE
raspberry connection issue

### PR DESCRIPTION
**Pull request by cagnulein**

### CODE REVIEW

**Comment by cagnulein** [comment]
@jonathancolledge do a
`git checkout raspberry`
and make it, it should work

**Comment by cagnulein** [comment]
#769

**Comment by cagnulein** [comment]
@jonathancolledge is it still ok?

**Comment by jonathancolledge** [comment]
Yes, it's working fine right now!

**Comment by cagnulein** [comment]
ok perfect, i will merge into the master so! thanks

**Pull request merged**
