### PR TITLE
Treadmill-modbus

### PR DESCRIPTION
**Pull request by jjbrough**
Linux with increased time

### CODE REVIEW

**Comment by cagnulein** [comment]
thanks my idea is to create one with these as settings. is it working?

**Comment by jjbrough** [comment]
I'm trying! I changed poolDeviceTime = 400 from 200. Is that the time that the switch is "on?" wasn't sure if it was that one or the GPIO_KEEP_MS =  50.

**Comment by cagnulein** [comment]
now that i'm thinking  of this i didn't finish to
implements the zwift api on linux. 
https://github.com/cagnulein/qdomyos-zwift/pull/1934
anyway let's build and check that you can change inclination from qz tile 

if you have a windows pc you can try auto inclination right now


going to bed now, we will discuss about this tomorrow

**Comment by jjbrough** [comment]
sounds good! I'll try on windows and we can figure out the Linux tmrw.

**Comment by cagnulein** [comment]
you can use the windows build that the github actions is building right now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 5 ott 2024 alle 22:26 jjbrough ***@***.***> ha
scritto:

**Comment by jjbrough** [comment]
Hey, just want to follow up.

Dosent look like the build worked. I can try to compile again, but is there
an issue with the source?

**Comment by cagnulein** [comment]
Share a debug log of the issue otherwise I can't see the issue
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 16 ott 2024 alle 22:56 jjbrough ***@***.***> ha
scritto:

> Hey, just want to follow up.
>
> Dosent look like the build worked. I can try to compile again, but is
> there
> an issue with the source?
>
>

**Comment by cagnulein** [comment]
ok which is the build error?

**Comment by jjbrough** [comment]
For the Windows build without Python:

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           10/5/2024  8:24 PM                output
d----           10/5/2024  8:24 PM                appx
Copy-Item: D:\a\_temp\217c0781-43ec-48fe-8ee5-c04439ad34ec.ps1:11
Line |
  11 |  cp qdomyos-zwift.exe output/
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'D:\a\qdomyos-zwift\qdomyos-zwift\src\debug\qdomyos-zwift.exe' because it does not exist.
Error: Process completed with exit code 1.


For linux build:

/opt/hostedtoolcache/Python/3.11.10/x64/bin/python3 -m aqt install-qt linux desktop 5.15.2 --outputdir /home/runner/work/qdomyos-zwift/Qt --modules qtnetworkauth qtcharts qtserial
INFO    : aqtinstall(aqt) v3.1.18 on Python 3.11.10 [CPython GCC 9.4.0]
WARNING : Specified modules ['qtserial'] did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
ERROR   : The packages ['qtserial'] were not found while parsing XML of package information!
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt linux desktop --modules 5.15.2 <arch>' to show modules available.
Error: Error: The process '/opt/hostedtoolcache/Python/3.11.10/x64/bin/python3' failed with exit code 1

**Comment by cagnulein** [comment]
No I mean aren't you building on raspberry?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 ott 2024 alle 23:48 jjbrough ***@***.***> ha
scritto:

**Comment by jjbrough** [comment]
I was going to, but I think you said above that the linux zwift api build wasn't complete yet.

**Comment by cagnulein** [comment]
Yeah that's right, in the meantime do you have a windows machine?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 18 ott 2024 alle 01:34 jjbrough ***@***.***> ha
scritto:

**Comment by jjbrough** [comment]
Yes I do! I can run it on windows in the meantime, but it just looks like when trying to compile it I got the error noted above.

**Comment by cagnulein** [comment]
@jjbrough check my comments in the review, you put some typos in the code

**Comment by jjbrough** [comment]
Reverted changes, now there is an issue resolving

**Pull request closed without merging**
