### PR TITLE
Android Srceen dimming Fix:

### PR DESCRIPTION
**Pull request by lifof**
Added a keepScreenOn function for Android to deactivate screen dimming

### CODE REVIEW

**Comment by cagnulein** [comment]
Thank you @lifof on which device did you test this?

**Comment by cagnulein** [comment]
#119

**Comment by lifof** [comment]
> Thank you @lifof on which device did you test this?

If your asking about what the app was tested on it's two devices, a Samsung galaxy tab 8 with android 10 and a Samsung galaxy S7 with android 8, otherwise if you're talking about the fitness machine that was used, it's a Domyos Elliptical trainer EL 500.

**Comment by cagnulein** [comment]
Yeah i was talking about android devices :)
Thanks, i will check on my side too!

Il gio 3 giu 2021, 09:49 lifof ***@***.***> ha scritto:

**Pull request merged**
